### ISSUE TITLE
threadingがエラーで終了する

### ISSUE THREAD

**Issue by hamuchan214** [hamuchan214/CN2024morigaki#19]
```bash
(3.12.7) hamuchan214@HarutonoMacBook-Air server % python mainapp.py
2024-11-22 12:52:47,635 - server - WARNING - Database setup completed successfully.
2024-11-22 12:52:47,635 - server - INFO - Server listening on 127.0.0.1:6001
^C^CServer shutting down.

^CException ignored in: <module 'threading' from '/Users/hamuchan214/.pyenv/versions/3.12.7/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/Users/hamuchan214/.pyenv/versions/3.12.7/lib/python3.12/threading.py", line 1594, in _shutdown
    atexit_call()
  File "/Users/hamuchan214/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/Users/hamuchan214/.pyenv/versions/3.12.7/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/Users/hamuchan214/.pyenv/versions/3.12.7/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
```

要検証
多分どっかのスレッドがちゃんと終了してないのにメインの関数を終わらせようとしてるからだと思う

**Comment by hamuchan214** [comment]
だいぶ前のコミットで修正済みのためクローズ
