### ISSUE TITLE
ターミナルの下までメッセージがいくと落ちる

### ISSUE THREAD

**Issue by hamuchan214** [hamuchan214/CN2024morigaki#4]
ターミナル下部までメッセージが溜まるとプログラムがクラッシュする。
以下ログ
```bash
Traceback (most recent call last):
  File "/Users/hamuchan214/Documents/GitHub/CN2024morigaki/client.py", line 130, in <module>
    curses.wrapper(start_client)
  File "/Users/hamuchan214/.pyenv/versions/3.12.7/lib/python3.12/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hamuchan214/Documents/GitHub/CN2024morigaki/client.py", line 113, in start_client
    client_socket.sendall(message.encode('utf-8'))  # ソケットが開いていることを確認して送信
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
hamuchan214@HarutonoMacBook-Air CN2024morigaki % python client.py
Traceback (most recent call last):
  File "/Users/hamuchan214/Documents/GitHub/CN2024morigaki/client.py", line 135, in <module>
    curses.wrapper(start_client)
  File "/Users/hamuchan214/.pyenv/versions/3.12.7/lib/python3.12/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hamuchan214/Documents/GitHub/CN2024morigaki/client.py", line 118, in start_client
    client_socket.sendall(message.encode('utf-8'))  # ソケットが開いていることを確認して送信
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
hamuchan214@HarutonoMacBook-Air CN2024morigaki % python client.py
Traceback (most recent call last):
  File "/Users/hamuchan214/Documents/GitHub/CN2024morigaki/client.py", line 135, in <module>
    curses.wrapper(start_client)
  File "/Users/hamuchan214/.pyenv/versions/3.12.7/lib/python3.12/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hamuchan214/Documents/GitHub/CN2024morigaki/client.py", line 93, in start_client
    stdscr.addstr(5 + i, 0, message[:curses.COLS-1])  # メッセージを表示（幅を制限）
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
```

**Comment by meru-muni** [comment]
ちわ

**Comment by meru-muni** [comment]
ちわわ（？）

**Comment by moririnUs** [comment]
範囲外にテキストを表示しようとすることでクラッシュしていた。
表示範囲や条件を調整することで、クラッシュせずにメッセージが更新されるようになった。

**Comment by hamuchan214** [comment]
コミットした？
履歴が見当たらん

**Comment by moririnUs** [comment]
コミットしました！

**Comment by hamuchan214** [comment]
https://github.com/hamuchan214/CN2024morigaki/pull/7
上記PRにて修正済みのためクローズ
